[WIP] [TEST] Setup test infrastructure
espressif/idf-im-cli pull request #51
Opened 2024-09-20 07:25 UTC by Fabricio-ESP

## Description

## Related

## Testing

---

## Checklist

Before submitting a Pull Request, please ensure the following:

- [X] 🚨 This PR does not introduce breaking changes.
- [ ] All CI checks (GH Actions) pass.
- [ ] Documentation is updated as needed.
- [ ] Tests are updated or added as necessary.
- [ ] Code is well-commented, especially in complex areas.
- [ ] Git history is clean — commits are squashed to the minimum necessary.

2024-10-29 13:17 UTC, Hahihula requested changes
The tests looks good to me, but at least the pipeline could be improved.

2024-10-29 17:24 UTC, Fabricio-ESP commented on .github/workflows/build_and_test.yaml
> +        branches:
Preferred the second approach to launch it after successful build.

2024-10-29 17:24 UTC, Fabricio-ESP commented on .github/workflows/build_and_test.yaml
> +    build:
Done it, agreed.

2024-10-29 17:28 UTC, Fabricio-ESP commented on .github/workflows/build_and_test.yaml
> +            # - name: downgrade powershell version (Windows)
Downgrade didn't work as is. I removed the commented code for now and will get back to this on next evolution.
Currently only the automatic pre-requisite installation on windows does not work, all other tests are executed.

2024-10-29 17:37 UTC, Fabricio-ESP commented on tests/README.md
> +`.\tests\run_test.ps1 "$env:USERPROFILE\espressif\eim.exe" "idf-im-cli 0.1.0"`
The version is set as an environmental variable, If using the build from master that was the version it was being printed. Would it be ok to update the instructions on the next iteraction?

2024-10-29 17:38 UTC, Fabricio-ESP commented on tests/classes/CLITestRunner.class.js
Right, I started as an independent code just for the post install test, but ended up using most of the features there.
I refactored this, and using a single class now, just an additional method to launch the shell instead of the IEM application.

2024-10-30 08:38 UTC, Hahihula commented on tests/README.md
> +`.\tests\run_test.ps1 "$env:USERPROFILE\espressif\eim.exe" "idf-im-cli 0.1.0"`
Sure, I didn't realize it's set by the ENV var so it does not brake anything

2024-10-30 08:39 UTC, Hahihula commented on tests/classes/CLITestRunner.class.js
Great work.

2024-10-30 10:44 UTC, merged